site_name: NotiLog
site_description: Масштабируемая и открытая система управления журналами приложений, процессами, нотификацией и эскалацией инцидентов.
site_author: Vladimir Penzin
site_url: https://www.notilog.ru/
repo_url: https://github.com/ForceFledgling/notilog
repo_name: github
edit_uri: blob/main/docs/
copyright: 2024, Vladimir Penzin

extra:
  version: "0.1"
  alternate:
    - name: Русский
      link: /
      lang: ru
    - name: English
      link: /en/ 
      lang: en

extra_css:
  - assets/styles/extra.css

theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  custom_dir: docs/overrides
  language: ru
  features:
    - content.action.edit  # кнопка редактирования
    - navigation.tabs  # меню
    - navigation.tabs.sticky  # меню - прибиваем к верху
    # - navigation.sections  # отображение всех страницы по разделам
    - navigation.footer  # навигация в футере
    - navigation.instant.progress  # отображает вверху прогресс загрузки страницы (для медленных соединений)
    - navigation.top  # добавляет кнопку прокрутки вверх
    - search.highlight  # выделяет вхождения поиска после перехода
    - search.share  # позволяет скопировать в буфер поисковый URL
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: yellow
      accent: cyan   
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: cyan      
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:  # Иконки следующей и предыдущей страниц
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

plugins:
  - search:
  - social:
  # - social:
  #     debug: false
  #     debug_color: yellow
  #     cards_layout: custom
  #     cards_layout_options:
  #       background_color: "#0FF1CE8F"
  #       background_image: layouts/stairs.jpg
  #       color: "#DE9151"
  #       font_family: Caveat
  - macros:
      module_name: macros
      on_error_fail: true
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_bases: false
            show_inheritance_diagram: true
            find_stubs_package: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Главная: index.md
  - Документация: docs/index.md
  - О приложении:
      - Обзор: docs/about/index.md
      - Архитектура:
          - Обзор: docs/architecture/index.md
          - Серверная часть: docs/architecture/server.md
          - Клиентская часть: docs/architecture/client.md
  - Установка:
      - Обзор: docs/installation-guide/index.md
      - Требования: docs/installation-guide/requirements.md
      - Руководство по установке: docs/installation-guide/installation.md
  - Руководства:
      - Обзор: docs/sections-overview/guides.md
      - Быстрый старт: docs/quickstart-guide/index.md
      - Часто задаваемые вопросы (FAQ): docs/guides/faq.md
  - Справочные материалы:
      - Обзор: docs/sections-overview/references.md
      - Концепции:
          - Обзор: docs/concepts/index.md
          - Основные концепции: docs/concepts/core.md
          - Примеры использования: docs/concepts/examples.md
  - Как сделать:
      - Обзор: docs/sections-overview/howto.md
      - Развертывание: docs/howto/deploy/index.md
      - Резервное копирование: docs/howto/backup/index.md
      - Обновление: docs/howto/update/index.md
  - Контакты:
      - Поддержка: docs/contact/support.md
      - Внести предложение: docs/contact/feedback.md
