# Site
site_name: NotiLog
site_description: Открытая cистема управления журналами приложений, мониторингом процессов, отправкой уведомлений и эскалацией инцидентов
site_author: Vladimir Penzin
site_url: https://www.notilog.ru/
copyright: 2024, Vladimir Penzin
docs_dir: .docs

# Repo
repo_url: https://github.com/ForceFledgling/notilog
repo_name: github
edit_uri: blob/main/docs/

extra:
  generator: false  # не отображать MkDocs copyright
  version: "v0.1-alpha"
  alternate:
    - name: Русский
      link: /
      lang: ru
    - name: English
      link: /en/ 
      lang: en
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/vpotd
      name: Vladimir Penzin on Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/ForceFledgling
      name: Vladimir Penzin on GitHub

extra_css:
  - assets/styles/extra.css

theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  custom_dir: .docs/overrides
  language: ru
  features:
    - content.action.edit           # кнопка редактирования
    - navigation.tabs               # меню
    - navigation.tabs.sticky        # меню - прибиваем к верху
    - navigation.footer             # навигация в футере
    - navigation.instant.progress   # отображает вверху прогресс загрузки страницы (для медленных соединений)
    - navigation.top                # добавляет кнопку прокрутки вверх
    - search.highlight              # выделяет вхождения поиска после перехода
    - search.share                  # позволяет скопировать в буфер поисковый URL
  palette:
    # Light mode
    - media: "(light)"
      scheme: slate
      primary: yellow
      accent: cyan   
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(dark)"
      scheme: default
      primary: yellow
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:  # Иконки следующей и предыдущей страниц
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil

plugins:
  - search:
  - macros:
      module_name: macros
      on_error_fail: true
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_bases: false
            show_inheritance_diagram: true
            find_stubs_package: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Главная: index.md
  - Документация:
      - Введение: d/intro.md
      - Назначение и цели: d/goals.md
      - Функциональные блоки: d/functional-blocks.md
      - Характеристики системы: d/characteristics.md
      - Документирование: d/docs.md
  - Регламенты:
      - Обзор: r/index.md
      - Резервное копирование и восстановление: r/backup-recovery.md
      - Плановое обслуживание системы: r/scheduled-maintenance.md
      - Действия при сбоях системы: r/system-failure-procedures.md
      - Эксплуатация системы : r/system-operation.md
      - Решение проблем и оптимизация: r/troubleshooting-optimization.md
      - Безопасность и лицензирование: r/security-licensing.md
  - Руководства:
      - Обзор: g/index.md
      - Пользователю: 
        - Введение: g/user/intro.md
      - Администратору: 
        - Введение: g/admin/intro.md
        - Быстрый старт: g/admin/quickstart.md
        - Установка: g/admin/install.md
        - Развертывание: g/admin/deploy.md
        - Миграции: g/admin/migration.md
      - Сообщество: g/community.md
  - Документация по API: http://backend.notilog.ru:9999/docs
  - Технические ссылки:
      - Обзор: t/index.md
      - Серверная часть:
        - Фронтенд: 
          - Обзор: t/server/frontend/index.md
          - API: t/server/frontend/api.md
          - Хранилише: t/server/frontend/storage.md
          - Представления: t/server/frontend/views.md
          - Мультиязычность: t/server/frontend/translate.md
        - Бэкенд: 
            - Обзор: t/server/backend/index.md
      - Клиентская часть: t/client/index.md
