site_name: NotiLog
nav:
  - Home: index.md

theme:
  name: material

plugins:
- mkdocstrings:
    enabled: true
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
          show_root_heading: true
          show_bases: false