# Site
site_name: NotiLog
site_description: Масштабируемая и открытая система управления журналами приложений, процессами, нотификацией и эскалацией инцидентов.
site_author: Vladimir Penzin
site_url: https://www.notilog.ru/
copyright: 2024, Vladimir Penzin

# Repo
repo_url: https://github.com/ForceFledgling/notilog
repo_name: github
edit_uri: blob/main/_docs/

extra:
  generator: false  # не отображать MkDocs copyright
  version: "0.1a"
  alternate:
    - name: Русский
      link: /
      lang: ru
    - name: English
      link: /en/ 
      lang: en
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/vpotd
      name: Vladimir Penzin on Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/ForceFledgling
      name: Vladimir Penzin on GitHub

extra_css:
  - assets/styles/extra.css

theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  custom_dir: docs/overrides
  language: ru
  features:
    - content.action.edit           # кнопка редактирования
    - navigation.tabs               # меню
    - navigation.tabs.sticky        # меню - прибиваем к верху
    - navigation.footer             # навигация в футере
    - navigation.instant.progress   # отображает вверху прогресс загрузки страницы (для медленных соединений)
    - navigation.top                # добавляет кнопку прокрутки вверх
    - search.highlight              # выделяет вхождения поиска после перехода
    - search.share                  # позволяет скопировать в буфер поисковый URL
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: yellow
      accent: cyan   
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: cyan      
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:  # Иконки следующей и предыдущей страниц
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil

plugins:
  - search:
  - macros:
      module_name: macros
      on_error_fail: true
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_bases: false
            show_inheritance_diagram: true
            find_stubs_package: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Главная: index.md
  - Документация:
      - Архитектура: _docs/index.md
      - Требования: _docs/requirements.md
      - Серверная часть:
        - Фронтенд: 
          - Обзор: _docs/server/frontend/index.md
          - API: _docs/server/frontend/api.md
          - Хранилише: _docs/server/frontend/storage.md
          - Представления: _docs/server/frontend/views.md
          - Мультиязычность: _docs/server/frontend/translate.md
        - Бэкенд: 
            - Обзор: _docs/server/backend/index.md
      - Клиентская часть: _docs/client/index.md
  - Руководства:
      - Обзор: _guides/index.md
      - Быстрый старт: _guides/quickstart.md
      - Установка: _guides/install.md
      - Развертывание: _guides/deploy.md
      - Миграции: _guides/migration.md
      - Резервное копирование: _guides/backup.md
      - Обновление: _guides/update.md
      - Концепции:
          - Обзор: _guides/concepts/index.md
          - Основные концепции: _guides/concepts/base.md
          - Примеры использования: _guides/concepts/examples.md
      - Руководство по сообществу: _guides/community.md
