site_name: NotiLog

theme:
  name: material
  logo: assets/logo.svg
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: amber
      # primary: blue-grey
      accent: amber
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      # primary: blue-grey
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# extra_css:
#   - overrides/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

plugins:
- mkdocstrings:
    enabled: true
    default_handler: python
    handlers:
      python:
        options:
          heading_level: 4
          docstring_style: google
          show_source: true
          show_root_heading: true
          show_bases: false
          show_inheritance_diagram: true
          find_stubs_package: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

nav:
    - Главная: index.md
    - О приложении:
        - Обзор: about/index.md
        - Архитектура:
            - Обзор: architecture/index.md
            - Серверная часть: architecture/server.md
            - Клиентская часть: architecture/client.md
    - Установка:
        - Обзор: installation-guide/index.md
        - Требования: installation-guide/requirements.md
        - Руководство по установке: installation-guide/installation.md
    - Руководства:
        - Обзор: sections-overview/guides.md
        - Быстрый старт: quickstart-guide/index.md
        - Часто задаваемые вопросы (FAQ): guides/faq.md
    - Справочные материалы:
        - Обзор: sections-overview/references.md
        - Концепции:
            - Обзор: concepts/index.md
            - Основные концепции: concepts/core.md
            - Примеры использования: concepts/examples.md
    - Как сделать:
        - Обзор: sections-overview/howto.md
        - Развертывание: howto/deploy/index.md
        - Резервное копирование: howto/backup/index.md
        - Обновление: howto/update/index.md
    - Контакты:
        - Поддержка: contact/support.md
        - Внести предложение: contact/feedback.md
