site_name: NotiLog
site_description: A service for receiving events, sending instant notifications, and incident escalation
site_author: Vladimir Penzin
site_url: https://www.notilog.ru/
repo_url: https://github.com/ForceFledgling/notilog
repo_name: github
copyright: 2024, Vladimir Penzin

extra:
  version: "0.1"

extra_css:
  - assets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

theme:
  name: material
  logo: assets/logo.svg
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: yellow
      accent: cyan   
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: cyan      
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - macros:
      module_name: macros
      on_error_fail: true
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_bases: false
            show_inheritance_diagram: true
            find_stubs_package: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
    - Главная: index.md
    - О приложении:
        - Обзор: about/index.md
        - Архитектура:
            - Обзор: architecture/index.md
            - Серверная часть: architecture/server.md
            - Клиентская часть: architecture/client.md
    - Установка:
        - Обзор: installation-guide/index.md
        - Требования: installation-guide/requirements.md
        - Руководство по установке: installation-guide/installation.md
    - Руководства:
        - Обзор: sections-overview/guides.md
        - Быстрый старт: quickstart-guide/index.md
        - Часто задаваемые вопросы (FAQ): guides/faq.md
    - Справочные материалы:
        - Обзор: sections-overview/references.md
        - Концепции:
            - Обзор: concepts/index.md
            - Основные концепции: concepts/core.md
            - Примеры использования: concepts/examples.md
    - Как сделать:
        - Обзор: sections-overview/howto.md
        - Развертывание: howto/deploy/index.md
        - Резервное копирование: howto/backup/index.md
        - Обновление: howto/update/index.md
    - Контакты:
        - Поддержка: contact/support.md
        - Внести предложение: contact/feedback.md
