"""create all tables

Revision ID: 000a90bb1b28
Revises: 50d35a51aab6
Create Date: 2024-09-14 18:45:12.166371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '000a90bb1b28'
down_revision: Union[str, None] = '50d35a51aab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_id'), 'api', ['id'], unique=False)
    op.create_index(op.f('ix_api_method'), 'api', ['method'], unique=False)
    op.create_index(op.f('ix_api_path'), 'api', ['path'], unique=False)
    op.create_index(op.f('ix_api_summary'), 'api', ['summary'], unique=False)
    op.create_index(op.f('ix_api_tags'), 'api', ['tags'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_method'), 'audit_log', ['method'], unique=False)
    op.create_index(op.f('ix_audit_log_module'), 'audit_log', ['module'], unique=False)
    op.create_index(op.f('ix_audit_log_path'), 'audit_log', ['path'], unique=False)
    op.create_index(op.f('ix_audit_log_response_time'), 'audit_log', ['response_time'], unique=False)
    op.create_index(op.f('ix_audit_log_status'), 'audit_log', ['status'], unique=False)
    op.create_index(op.f('ix_audit_log_summary'), 'audit_log', ['summary'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_username'), 'audit_log', ['username'], unique=False)
    op.create_table('dept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dept_id'), 'dept', ['id'], unique=False)
    op.create_index(op.f('ix_dept_is_deleted'), 'dept', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dept_name'), 'dept', ['name'], unique=True)
    op.create_index(op.f('ix_dept_order'), 'dept', ['order'], unique=False)
    op.create_index(op.f('ix_dept_parent_id'), 'dept', ['parent_id'], unique=False)
    op.create_table('dept_closure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ancestor', sa.Integer(), nullable=True),
    sa.Column('descendant', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dept_closure_ancestor'), 'dept_closure', ['ancestor'], unique=False)
    op.create_index(op.f('ix_dept_closure_descendant'), 'dept_closure', ['descendant'], unique=False)
    op.create_index(op.f('ix_dept_closure_id'), 'dept_closure', ['id'], unique=False)
    op.create_index(op.f('ix_dept_closure_level'), 'dept_closure', ['level'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('remark', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('menu_type', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('keepalive', sa.Boolean(), nullable=True),
    sa.Column('redirect', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=False)
    op.create_index(op.f('ix_menu_order'), 'menu', ['order'], unique=False)
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_menu_path'), 'menu', ['path'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('role_api',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('role_menu',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('alias', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['dept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_alias'), 'user', ['alias'], unique=False)
    op.create_index(op.f('ix_user_dept_id'), 'user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_is_superuser'), 'user', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_user_last_login'), 'user', ['last_login'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_last_login'), table_name='user')
    op.drop_index(op.f('ix_user_is_superuser'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_dept_id'), table_name='user')
    op.drop_index(op.f('ix_user_alias'), table_name='user')
    op.drop_table('user')
    op.drop_table('role_menu')
    op.drop_table('role_api')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_menu_path'), table_name='menu')
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_order'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_dept_closure_level'), table_name='dept_closure')
    op.drop_index(op.f('ix_dept_closure_id'), table_name='dept_closure')
    op.drop_index(op.f('ix_dept_closure_descendant'), table_name='dept_closure')
    op.drop_index(op.f('ix_dept_closure_ancestor'), table_name='dept_closure')
    op.drop_table('dept_closure')
    op.drop_index(op.f('ix_dept_parent_id'), table_name='dept')
    op.drop_index(op.f('ix_dept_order'), table_name='dept')
    op.drop_index(op.f('ix_dept_name'), table_name='dept')
    op.drop_index(op.f('ix_dept_is_deleted'), table_name='dept')
    op.drop_index(op.f('ix_dept_id'), table_name='dept')
    op.drop_table('dept')
    op.drop_index(op.f('ix_audit_log_username'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_summary'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_status'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_response_time'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_path'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_module'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_method'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_tags'), table_name='api')
    op.drop_index(op.f('ix_api_summary'), table_name='api')
    op.drop_index(op.f('ix_api_path'), table_name='api')
    op.drop_index(op.f('ix_api_method'), table_name='api')
    op.drop_index(op.f('ix_api_id'), table_name='api')
    op.drop_table('api')
    # ### end Alembic commands ###
