"""create event table

Revision ID: 7534c88cafa4
Revises: e8406cbf6b19
Create Date: 2024-09-24 02:33:48.529445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '7534c88cafa4'
down_revision: Union[str, None] = 'e8406cbf6b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_correlation_id'), 'event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_environment'), 'event', ['environment'], unique=False)
    op.create_index(op.f('ix_event_host'), 'event', ['host'], unique=False)
    op.create_index(op.f('ix_event_request_id'), 'event', ['request_id'], unique=False)
    op.create_index(op.f('ix_event_service'), 'event', ['service'], unique=False)
    op.create_index(op.f('ix_event_source'), 'event', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_source'), table_name='event')
    op.drop_index(op.f('ix_event_service'), table_name='event')
    op.drop_index(op.f('ix_event_request_id'), table_name='event')
    op.drop_index(op.f('ix_event_host'), table_name='event')
    op.drop_index(op.f('ix_event_environment'), table_name='event')
    op.drop_index(op.f('ix_event_correlation_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
