"""тест

Revision ID: e8406cbf6b19
Revises: 000a90bb1b28
Create Date: 2024-09-14 20:46:55.272535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8406cbf6b19'
down_revision: Union[str, None] = '000a90bb1b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('api', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('audit_log', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dept', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('dept', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dept_closure', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('dept_closure', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('menu', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('menu', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('role', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_column('menu', 'updated_at')
    op.drop_column('menu', 'created_at')
    op.drop_column('dept_closure', 'updated_at')
    op.drop_column('dept_closure', 'created_at')
    op.drop_column('dept', 'updated_at')
    op.drop_column('dept', 'created_at')
    op.drop_column('audit_log', 'updated_at')
    op.drop_column('audit_log', 'created_at')
    op.drop_column('api', 'updated_at')
    op.drop_column('api', 'created_at')
    # ### end Alembic commands ###
