"""changed events

Revision ID: bb15e77df77a
Revises: 24ac4e8f87ad
Create Date: 2024-10-19 02:59:21.931416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb15e77df77a'
down_revision = '24ac4e8f87ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
